### ISSUE TITLE
[question] Change Ignition Configuration?

### ISSUE THREAD

**Issue by TheAlgorythm** [jimlee2048/fedora-coreos-proxmox#1]
What is the best process to to change the ignite configuration in order to change something like adding a podman service?
If I have multiple different VMs, should I create a template per use-case?

**Comment by jimlee2048** [comment]
Sorry for response your issue slowly. Although I'm not the developer who write this script, also lacking knowledge about shell scripting and ignite configuration, I would like to try my best to answer your question.

> What is the best process to to change the ignite configuration in order to change something like adding a podman service?

This project using [butane](https://github.com/coreos/butane) to generate ignite config. It first generate a butane config according you parameter provided in `template_deploy.conf`, then using this generated butane config to get a ignite config.

The butane config is combined from these two script. So using these scripts, if you want to change the ignite config used by CoreOS VM, you may need to modify them manually. Note that you should be careful about indentation.

1. `hook-fcos.sh`: 
https://github.com/jimlee2002/fedora-coreos-proxmox/blob/2db993cc46245fc6f8cb1425c9e730f6c35ffdcf/hook-fcos.sh#L68-L145
It's generate the leading part of the butane config, the output from this script structured like:
```yaml
variant: fcos
version: 1.1.0
passwd:
  users:
    (...)
storage:
  files:
    (...)
```

2. `fcos-base-tmplt.yaml`:
https://github.com/jimlee2002/fedora-coreos-proxmox/blob/master/fcos-base-tmplt.yaml
It define the last part of the butane config. The config writing here would be directly append to the first part generated from `hook-fcos.sh`, which mean the butane config you finally get look like this:
```yaml
variant: fcos
version: 1.1.0
passwd:
  users:
    (...)
storage:
  files:
    (...) # some of them already define in `hook-fcos.sh`
    (...) # the other part would be append from `fcos-base-tmplt.yaml`
(...) # the other part you may add in `fcos-base-tmplt.yaml`
```

> If I have multiple different VMs, should I create a template per use-case?

I think it depends on your personal needs, like if you need some special templates to pre init some services not just using a universal template.
